image: Visual Studio 2017

environment:
  global:
    RUST_VERSION: stable

  matrix:
    # MSVC
    - TARGET: i686-pc-windows-msvc
      OPENSSL_DIR: C:\OpenSSL-v111-Win32
      OPENSSL_LIBS: libssl_static:libcrypto_static
      OPENSSL_STATIC: 1
    - TARGET: x86_64-pc-windows-msvc
      OPENSSL_DIR: C:\OpenSSL-v111-Win64
      OPENSSL_LIBS: libssl_static:libcrypto_static
      OPENSSL_STATIC: 1

    # MinGW
    - TARGET: i686-pc-windows-gnu
      BITS: 32
      MSYS2: 1
    - TARGET: x86_64-pc-windows-gnu
      BITS: 64
      MSYS2: 1

install:
  # Install Rust
  - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

build_script:
  - cargo build --target %TARGET%
  - cargo build --target %TARGET% --release

test_script:
  - cargo test --target %TARGET%

artifacts:
  - path: target\%TARGET%\debug\armake2.exe
  - path: target\%TARGET%\release\armake2.exe

cache:
  - C:\Users\appveyor\.cargo\registry
  - target
